blank_issues_enabled: false
contact_links:
  - name: Report a Website Issue
    url: https://github.com/nucleus-bot/website/issues
    about: For anything related to nucleus.bot in the browser; The website, the dashboard, or the API
  - name: Report a Translation Issue
    url: https://github.com/nucleus-bot/translations/issues
    about: For anything related to the spelling or grammar of chat messages or website content
